// src/lib/draws.js
// Last updated: After Day 3 (May 26, 2026) — R1 complete, R2 added

export const TOURNAMENTS = [
  {
    id: "french-open-2026",
    name: "French Open",
    year: 2026,
    surface: "Clay",
    dates: "May 24 – June 7, 2026",
    location: "Paris, France",
    status: "live",
    theme: {
      primary: "#c1440e", primaryDark: "#8b2e07", primaryLight: "#e8602a",
      accent: "#f0a030", bg: "#1a0a05", surface: "#2a1208", card: "#1e0e06",
      border: "#5a3020", text: "#e8d5a3", textDim: "#9a7055", white: "#fdf8f0", emoji: "🎾",
    },
  },
  {
    id: "wimbledon-2026",
    name: "Wimbledon", year: 2026, surface: "Grass",
    dates: "June 29 – July 12, 2026", location: "London, England", status: "upcoming",
    theme: {
      primary: "#2d6a2d", primaryDark: "#1a4a1a", primaryLight: "#4a8f4a",
      accent: "#9b59b6", bg: "#080f08", surface: "#0f1f0f", card: "#0c180c",
      border: "#2d5a2d", text: "#c8e6c8", textDim: "#6a9a6a", white: "#f0faf0", emoji: "🌿",
    },
  },
  {
    id: "us-open-2026",
    name: "US Open", year: 2026, surface: "Hard",
    dates: "Aug 31 – Sep 13, 2026", location: "New York, USA", status: "upcoming",
    theme: {
      primary: "#002b7f", primaryDark: "#001a55", primaryLight: "#0040bf",
      accent: "#e8c830", bg: "#05080f", surface: "#0a1020", card: "#080d1a",
      border: "#1a2a50", text: "#c8d8f0", textDim: "#5a7a9a", white: "#f0f5ff", emoji: "🇺🇸",
    },
  },
  {
    id: "australian-open-2027",
    name: "Australian Open", year: 2027, surface: "Hard",
    dates: "Jan 18 – Feb 1, 2027", location: "Melbourne, Australia", status: "upcoming",
    theme: {
      primary: "#0057a8", primaryDark: "#003d7a", primaryLight: "#1a70c8",
      accent: "#f0c020", bg: "#030810", surface: "#080f1e", card: "#060c18",
      border: "#1a2a45", text: "#c0d8f8", textDim: "#4a6a8a", white: "#f0f8ff", emoji: "🦘",
    },
  },
];

export const ROUND_POINTS = { R128: 10, R64: 20, R32: 40, R16: 80, QF: 160, SF: 320, F: 640 };
export const ROUNDS = ["R128", "R64", "R32", "R16", "QF", "SF", "F"];
export const ROUND_LABELS = {
  R128: "1st Round", R64: "2nd Round", R32: "3rd Round",
  R16: "Round of 16", QF: "Quarterfinals", SF: "Semifinals", F: "Final",
};

// ─── ROUND 1 — ALL COMPLETE ───────────────────────────────────────────────────
const FO2026_R1 = [
  { id: 1,  p1: "J. Sinner [1]",             p2: "C. Tabur (WC)",          status: "complete", winner: "J. Sinner [1]" },
  { id: 2,  p1: "J. Fearnley",               p2: "J.M. Cerundolo",         status: "complete", winner: "J.M. Cerundolo" },
  { id: 3,  p1: "M. Landaluce",              p2: "J.C. Prado Ángelo (Q)",  status: "complete", winner: "M. Landaluce" },
  { id: 4,  p1: "V. Kopriva",                p2: "C. Moutet [30]",         status: "complete", winner: "V. Kopriva" },
  { id: 5,  p1: "A. Rinderknech [22]",       p2: "J. Rodionov (Q)",        status: "complete", winner: "A. Rinderknech [22]" },
  { id: 6,  p1: "M. Fucsovics",              p2: "M. Berrettini",          status: "complete", winner: "M. Berrettini" },
  { id: 7,  p1: "E. Quinn",                  p2: "F. Comesana",            status: "complete", winner: "F. Comesana" },
  { id: 8,  p1: "S. Ofner",                  p2: "L. Darderi [14]",        status: "complete", winner: "L. Darderi [14]" },
  { id: 9,  p1: "A. Bublik [9]",             p2: "J-L. Struff",            status: "complete", winner: "J-L. Struff" },
  { id: 10, p1: "J. Faria (Q)",              p2: "D. Shapovalov",          status: "complete", winner: "J. Faria (Q)" },
  { id: 11, p1: "J. Munar",                  p2: "H. Hurkacz",             status: "complete", winner: "H. Hurkacz" },
  { id: 12, p1: "E. Spizzirri",              p2: "F. Tiafoe [19]",         status: "complete", winner: "F. Tiafoe [19]" },
  { id: 13, p1: "T. Griekspoor [29]",        p2: "M. Arnaldi",             status: "complete", winner: "M. Arnaldi" },
  { id: 14, p1: "A. Muller",                 p2: "S. Tsitsipas",           status: "complete", winner: "S. Tsitsipas" },
  { id: 15, p1: "R. Collignon",              p2: "A. Vukic",               status: "complete", winner: "R. Collignon" },
  { id: 16, p1: "D. Merida",                 p2: "B. Shelton [5]",         status: "complete", winner: "B. Shelton [5]" },
  { id: 17, p1: "S. Báez",                   p2: "R.A. Burruchaga",        status: "complete", winner: "R.A. Burruchaga" },
  { id: 18, p1: "L. Van Assche",             p2: "P. Kypson",              status: "complete", winner: "L. Van Assche" },
  { id: 19, p1: "R. Bautista Agut",          p2: "B. Nakashima [31]",      status: "complete", winner: "B. Nakashima [31]" },
  { id: 20, p1: "C. Norrie [20]",            p2: "A.D. Vallejo",           status: "complete", winner: "A.D. Vallejo" },
  { id: 21, p1: "M. Cilic",                  p2: "M. Kouamé (WC)",         status: "complete", winner: "M. Kouamé (WC)" },
  { id: 22, p1: "A. Tabilo",                 p2: "K. Majchrzak",           status: "complete", winner: "A. Tabilo" },
  { id: 23, p1: "T. Faurel (Q)",             p2: "V. Vacherot [16]",       status: "complete", winner: "V. Vacherot [16]" },
  { id: 24, p1: "F. Cobolli [10]",           p2: "A. Pellegrino (Q)",      status: "complete", winner: "F. Cobolli [10]" },
  { id: 25, p1: "Y. Wu",                     p2: "M. Giron",               status: "complete", winner: "Y. Wu" },
  { id: 26, p1: "F. Diaz Acosta (Q)",        p2: "Z. Zhang",               status: "complete", winner: "F. Diaz Acosta (Q)" },
  { id: 27, p1: "C. Garin",                  p2: "L. Tien [18]",           status: "complete", winner: "L. Tien [18]" },
  { id: 28, p1: "F. Cerundolo [25]",         p2: "B. Van De Zandschulp",   status: "complete", winner: "F. Cerundolo [25]" },
  { id: 29, p1: "H. Gaston (WC)",            p2: "G. Monfils (WC)",        status: "complete", winner: "H. Gaston (WC)" },
  { id: 30, p1: "A. Popyrin",                p2: "Z. Svajda",              status: "complete", winner: "Z. Svajda" },
  { id: 31, p1: "A. Walton (WC)",            p2: "D. Medvedev [6]",        status: "complete", winner: "A. Walton (WC)" },
  { id: 32, p1: "J. de Jong (LL)",           p2: "S. Wawrinka",            status: "complete", winner: "J. de Jong (LL)" },
  { id: 33, p1: "A. De Minaur [8]",          p2: "T. Samuel (Q)",          status: "complete", winner: "A. De Minaur [8]" },
  { id: 34, p1: "A. Blockx",                 p2: "C. Wong (LL)",           status: "complete", winner: "A. Blockx" },
  { id: 35, p1: "M. Navone",                 p2: "J. Brooksby",            status: "complete", winner: "M. Navone" },
  { id: 36, p1: "T. Droguet (WC)",           p2: "J. Mensik [26]",         status: "complete", winner: "J. Mensik [26]" },
  { id: 37, p1: "T.M. Etcheverry [23]",      p2: "N. Borges",              status: "complete", winner: "N. Borges" },
  { id: 38, p1: "M. Kecmanovic",             p2: "F. Marozsan",            status: "complete", winner: "M. Kecmanovic" },
  { id: 39, p1: "E. Nava (Q)",               p2: "C. Ugo Carabelli",       status: "complete", winner: "C. Ugo Carabelli" },
  { id: 40, p1: "I. Buse",                   p2: "A. Rublev [11]",         status: "complete", winner: "A. Rublev [11]" },
  { id: 41, p1: "C. Ruud [15]",              p2: "R. Safiullin (Q)",       status: "complete", winner: "C. Ruud [15]" },
  { id: 42, p1: "H. Medjedovic",             p2: "Y. Hanfmann",            status: "complete", winner: "H. Medjedovic" },
  { id: 43, p1: "L. Sonego",                 p2: "P-H. Herbert (Q)",       status: "complete", winner: "L. Sonego" },
  { id: 44, p1: "R. Hijikata",               p2: "T. Paul [24]",           status: "complete", winner: "T. Paul [24]" },
  { id: 45, p1: "J. Fonseca [28]",           p2: "L. Pavlovic (Q)",        status: "complete", winner: "J. Fonseca [28]" },
  { id: 46, p1: "M. Zheng (Q)",              p2: "D. Prizmic",             status: "complete", winner: "D. Prizmic" },
  { id: 47, p1: "H. Dellien (Q)",            p2: "V. Royer",               status: "complete", winner: "V. Royer" },
  { id: 48, p1: "G. Mpetshi Perricard",      p2: "N. Djokovic [3]",        status: "complete", winner: "N. Djokovic [3]" },
  { id: 49, p1: "T. Fritz [7]",              p2: "N. Basavareddy (WC)",    status: "complete", winner: "N. Basavareddy (WC)" },
  { id: 50, p1: "A. Shevchenko",             p2: "A. Michelsen",           status: "complete", winner: "A. Michelsen" },
  { id: 51, p1: "J. Duckworth",              p2: "G. Diallo",              status: "complete", winner: "J. Duckworth" },
  { id: 52, p1: "A. Kovacevic",              p2: "R. Jodar [27]",          status: "complete", winner: "R. Jodar [27]" },
  { id: 53, p1: "F. Auger-Aliassime [4]",    p2: "D. Altmaier",            status: "complete", winner: "F. Auger-Aliassime [4]" },
  { id: 54, p1: "A. Davidovich Fokina [21]", p2: "T.A. Tirante",           status: "complete", winner: "A. Davidovich Fokina [21]" },
  { id: 55, p1: "K. Khachanov [13]",         p2: "M. Trungelliti",         status: "complete", winner: "K. Khachanov [13]" },
  { id: 56, p1: "P. Carreno Busta",          p2: "J. Lehečka [12]",        status: "complete", winner: "P. Carreno Busta" },
  { id: 57, p1: "T. Kokkinakis",             p2: "T. Atmane",              status: "complete", winner: "T. Kokkinakis" },
  { id: 58, p1: "U. Humbert [32]",           p2: "A. Mannarino",           status: "complete", winner: "U. Humbert [32]" },
  { id: 59, p1: "T. Machac",                 p2: "Z. Bergs",               status: "complete", winner: "T. Machac" },
  { id: 60, p1: "A. Zverev [2]",             p2: "B. Bonzi",               status: "complete", winner: "A. Zverev [2]" },
  { id: 61, p1: "F. Cina",                   p2: "J. de Jong (LL)",        status: "complete", winner: "J. de Jong (LL)" },
  { id: 62, p1: "N. Basavareddy (WC)",       p2: "A. Michelsen",           status: "complete", winner: "N. Basavareddy (WC)" },
  { id: 63, p1: "T. Kokkinakis",             p2: "P. Carreno Busta",       status: "complete", winner: "P. Carreno Busta" },
  { id: 64, p1: "U. Humbert [32]",           p2: "Q. Halys",               status: "complete", winner: "U. Humbert [32]" },
];

// ─── ROUND 2 — PICKS OPEN, NO RESULTS YET ────────────────────────────────────
const FO2026_R2 = [
  // TOP HALF
  { id: 1,  p1: "J. Sinner [1]",             p2: "J.M. Cerundolo",         status: "upcoming", winner: null },
  { id: 2,  p1: "M. Landaluce",              p2: "V. Kopriva",             status: "upcoming", winner: null },
  { id: 3,  p1: "A. Rinderknech [22]",       p2: "M. Berrettini",          status: "upcoming", winner: null },
  { id: 4,  p1: "F. Comesana",               p2: "L. Darderi [14]",        status: "upcoming", winner: null },
  { id: 5,  p1: "J-L. Struff",               p2: "J. Faria (Q)",           status: "upcoming", winner: null },
  { id: 6,  p1: "H. Hurkacz",                p2: "F. Tiafoe [19]",         status: "upcoming", winner: null },
  { id: 7,  p1: "M. Arnaldi",                p2: "S. Tsitsipas",           status: "upcoming", winner: null },
  { id: 8,  p1: "R. Collignon",              p2: "B. Shelton [5]",         status: "upcoming", winner: null },
  { id: 9,  p1: "R.A. Burruchaga",           p2: "L. Van Assche",          status: "upcoming", winner: null },
  { id: 10, p1: "B. Nakashima [31]",         p2: "A.D. Vallejo",           status: "upcoming", winner: null },
  { id: 11, p1: "M. Kouamé (WC)",            p2: "A. Tabilo",              status: "upcoming", winner: null },
  { id: 12, p1: "V. Vacherot [16]",          p2: "F. Cobolli [10]",        status: "upcoming", winner: null },
  { id: 13, p1: "Y. Wu",                     p2: "F. Diaz Acosta (Q)",     status: "upcoming", winner: null },
  { id: 14, p1: "L. Tien [18]",              p2: "F. Cerundolo [25]",      status: "upcoming", winner: null },
  { id: 15, p1: "H. Gaston (WC)",            p2: "Z. Svajda",              status: "upcoming", winner: null },
  { id: 16, p1: "A. Walton (WC)",            p2: "J. de Jong (LL)",        status: "upcoming", winner: null },
  // BOTTOM HALF
  { id: 17, p1: "A. De Minaur [8]",          p2: "A. Blockx",              status: "upcoming", winner: null },
  { id: 18, p1: "M. Navone",                 p2: "J. Mensik [26]",         status: "upcoming", winner: null },
  { id: 19, p1: "N. Borges",                 p2: "M. Kecmanovic",          status: "upcoming", winner: null },
  { id: 20, p1: "C. Ugo Carabelli",          p2: "A. Rublev [11]",         status: "upcoming", winner: null },
  { id: 21, p1: "C. Ruud [15]",              p2: "H. Medjedovic",          status: "upcoming", winner: null },
  { id: 22, p1: "L. Sonego",                 p2: "T. Paul [24]",           status: "upcoming", winner: null },
  { id: 23, p1: "J. Fonseca [28]",           p2: "D. Prizmic",             status: "upcoming", winner: null },
  { id: 24, p1: "V. Royer",                  p2: "N. Djokovic [3]",        status: "upcoming", winner: null },
  { id: 25, p1: "N. Basavareddy (WC)",        p2: "A. Michelsen",           status: "upcoming", winner: null },
  { id: 26, p1: "J. Duckworth",              p2: "R. Jodar [27]",          status: "upcoming", winner: null },
  { id: 27, p1: "F. Auger-Aliassime [4]",    p2: "R.A. Burruchaga",              status: "upcoming", winner: null },
  { id: 28, p1: "K. Khachanov [13]",         p2: "P. Carreno Busta",       status: "upcoming", winner: null },
  { id: 29, p1: "T. Kokkinakis",             p2: "U. Humbert [32]",        status: "upcoming", winner: null },
  { id: 30, p1: "T. Machac",                 p2: "A. Zverev [2]",          status: "upcoming", winner: null },
  { id: 31, p1: "J. de Jong (LL)",           p2: "F. Cina",                status: "upcoming", winner: null },
  { id: 32, p1: "N. Basavareddy (WC) (B)",   p2: "P. Carreno Busta (B)",   status: "upcoming", winner: null },
];

export const DRAWS = {
  "french-open-2026": {
    R128: FO2026_R1,
    R64:  FO2026_R2,
    R32:  [],
    R16:  [],
    QF:   [],
    SF:   [],
    F:    [],
  },
  "wimbledon-2026": null,
  "us-open-2026":   null,
  "australian-open-2027": null,
};
